package dsw.rudok.app.ErrorHandler;

public enum ErrorTypes {
    SELECTIONERROR,ACTIONERROR,SLOTERROR,WORKSPACEERROR,WORKSPACENOTSELECTED,DOCUMENTERROR,PAGEERROR,NOTPAGESELECTED,ROTATECIRCLEERROR,SLOTNOTSELECTED
}
