package dsw.rudok.app.commands;

public enum CommandsEnum {
    RECTANGLE,TRIANGLE,CIRCLE,DELETE,SELECT,MOVE,ROTATE,RESIZE,MULTISELEKT,COMMANDNULL,CURRENTSMALLER,DELETEDO,CURRENTCOMMANDEQUAL,MULTISELEKTUNDO,UNDODELETE,UNDOELEMENTS,UNDOMOVE,ROOT
}